version: '3.5'

services:

  spring-app:
    image: abdprojekt/web
    ports:
    - 8080:8080
    depends_on:
    - soadb

  soadb:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
    - 1521:1521
    - 5500:5500
    environment:
    - ORACLE_SID=soadb
    - ORACLE_PDB=soapdb
    - ORACLE_PWD=password
    container_name: soadb
